language: rust

rust:
  - nightly
  - stable

cache:
  - cargo
  - apt
#  cache:
#    directories:
#      - $HOME/.cache/pip

sudo: required

env:
  global:
    - RUST_BACKTRACE=FULL
    - RUSTFLAGS="-Ctarget-cpu=native"
    - RUST_MIN_STACK=8000000
#    - RUST_TEST_THREADS=1


#addons:
#  apt:
#    packages:
#      - libcurl4-openssl-dev
#      - libelf-dev
#      - libdw-dev
#      - binutils-dev
#      - cmake
#    sources:
#      - kalakris-cmake

os:
  - linux

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ];
    then
      cargo build --verbose --package pleco;
      cargo test --package pleco;
      cargo build --package pleco;
    else
      cargo build --verbose;
      cargo test;
      cargo bench --package pleco --all-features;
      cargo bench --package pleco_engine --all-features;
    fi

#  - cargo build --verbose
#  - echo " ------ TESTING STABLE BRANCH ------- "
#  - cargo +stable test --package pleco
#  - cargo +stable bench --package pleco
#  - echo " ------ TESTING NIGHTLY BRANCH ------- "
#  - cargo test --verbose
#  - cargo bench --package pleco --all-features
#  - cargo bench --package pleco_engine --all-features

#after_success:
#  - |
#    if [[ "$TRAVIS_BRANCH" = "master" ]] AND [ "$TRAVIS_PULL_REQUEST" = "false" ]
#    then
#      cargo install cargo-travis || echo "cargo-travis has been already installed"
#      export PATH=$HOME/.cargo/bin:$PATH
#      cargo coveralls
#    fi
#
