language: rust

rust:
  - nightly


cache:
  - cargo
  - apt


sudo: required
dist: trusty
group: deprecated-2017Q4

env:
  global:
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake


os:
  - linux


script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
    then
        cargo bench
    fi
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
        cargo doc
    fi



after_success:
  - |
    if [[ "$TRAVIS_BRANCH" != "Beta-Branch" ]]
    then
      cargo install cargo-travis || echo "cargo-travis has been already installed"
      export PATH=$HOME/.cargo/bin:$PATH
      cargo coveralls
    fi

