language: rust

rust:
  - nightly


cache:
  - cargo
  - apt

sudo: required

env:
  global:
    - RUST_BACKTRACE=FULL
    - RUSTFLAGS="-Zmir-opt-level=3"
#    - RUSTFLAGS="-Ctarget-cpu=native -Zthinlto=on -Zmir-opt-level=3 -Zmutable-noalias"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake


os:
  - linux

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" != "Beta-Branch" ]]
    then
      cargo install cargo-travis || echo "cargo-travis has been already installed"
      export PATH=$HOME/.cargo/bin:$PATH
      cargo coveralls
    fi

