language: rust

rust:
  - nightly
  - stable

cache:
  - cargo
  - apt
#  cache:
#    directories:
#      - $HOME/.cache/pip

sudo: required

env:
  global:
    - RUST_BACKTRACE=FULL
    - RUSTFLAGS="-Ctarget-cpu=native"
    - RUST_MIN_STACK=8000000
#    - RUST_TEST_THREADS=1

os:
  - linux

script:
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ];
    then
      cargo build --verbose --package pleco;
      cargo test --package pleco;
      cargo bench --package pleco;
    else
      cargo build --verbose;
      cargo test;
      cargo bench --package pleco --all-features;
      cargo bench --package pleco_engine --all-features;
    fi

#  - cargo build --verbose
#  - echo " ------ TESTING STABLE BRANCH ------- "
#  - cargo +stable test --package pleco
#  - cargo +stable bench --package pleco
#  - echo " ------ TESTING NIGHTLY BRANCH ------- "
#  - cargo test --verbose
#  - cargo bench --package pleco --all-features
#  - cargo bench --package pleco_engine --all-features
