[package]
name = "Pleco"
version = "0.1.0"
authors = ["stephenf <stephenf@cs.washington.edu>"]

include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    ".gitignore"
]

[lib]
name = "Pleco"

[dependencies]
clippy = {version = "*", optional = true}
lazy_static = "0.2"
chashmap = {version = "*"}
bitflags = {version = "*"}
rand = "0.3"
chrono = "0.4"
rayon = {version = "*"}

[features]
default = []

[[test]]
path = "tests/test.rs"
name = "default"