[package]
name = "Pleco"
version = "0.1.0"
authors = ["stephenf <stephenf@cs.washington.edu>"]

include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    ".gitignore"
]

[profile.dev]
opt-level = 3

[profile.release]
debug = true

[lib]
name = "Pleco"

[dependencies]
clippy = {version = "*", optional = true}
lazy_static = "0.2"
chashmap = {version = "*"}
bitflags = "0.9"
rand = "0.3"
chrono = "0.4"
rayon = "0.8.2"
futures = "0.1.14"

[features]
default = []

[[test]]
path = "tests/test.rs"
name = "default"